task_manager/statuses/tests.py
task_manager/labels/tests.py
task_manager/labels/views.py
task_manager/statuses/views.py
task_manager/labels/migrations/0001_initial.py
task_manager/statuses/migrations/0001_initial.py
task_manager/statuses/urls.py
task_manager/labels/urls.py
task_manager/statuses/forms.py
task_manager/labels/forms.py
task_manager/labels/models.py
task_manager/statuses/models.py