name: pyci

on: [push]

jobs:
  run-linters:
    name: Run linter and pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
           pip install poetry
           poetry update
           make install
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ROLLBAR_KEY: ${{ secrets.ROLLBAR_TOKEN }}
          DEBUG: True
        run: |
           make test
      - name: code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
      - name: Run linter
        run: |
           make lint